Create [HuberStefan].md
HuberStefan/github-fundamentels-training pull request #9
Opened 2023-11-28 15:46 UTC by HuberStefan

Test

2023-11-28 15:47 UTC, HuberStefan commented on docs/_slides/[HuberStefan].md
> +Greetings from [username]!
Hey @kieblerto passt das so für dich?

2023-11-28 15:54 UTC, kieblerto requested changes

2023-11-29 08:18 UTC, kieblerto commented on docs/_slides/[HuberStefan].md
> +![dinotocat](https://octodex.github.com/images/dinotocat.png)
```suggestion
![dinotocat](https://octodex.github.com/images/saint_nictocat.jpg)
```

It's time for christmas

2023-11-29 08:24 UTC, HuberStefan reviewed
Nice suggestion

2023-11-29 09:07 UTC, kieblerto approved these changes

2023-11-29 09:10 UTC, kieblerto requested changes

2023-11-29 09:10 UTC, kieblerto commented on docs/_slides/[HuberStefan].md
> +{: .center}
no new line at EOF

2023-11-29 09:15 UTC, kieblerto approved these changes

2023-11-29 09:15 UTC, merged